/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        background: "var(--color-bg)",
        surface: "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "surface-variant": "var(--color-surface-variant)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "on-background": "var(--color-on-bg)",
        outline: "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        primary: "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "surface-tint": "var(--color-surface-tint)",
        secondary: "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        tertiary: "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        error: "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        "accent-emerald": "#10b981",
        "accent-teal": "#14b8a6",
        "accent-cyan": "#06b6d4",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        sm: "0.25rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
        "2xl": "2rem",
        full: "9999px",
      },
      spacing: {
        "container-max": "1300px",
        gutter: "24px",
        "margin-mobile": "20px",
        "section-gap": "100px",
        "stack-xs": "4px",
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-xl": "64px",
      },
      fontFamily: {
        sans: ["Geist", "-apple-system", "BlinkMacSystemFont", "sans-serif"],
        display: ["Geist", "sans-serif"],
        body: ["Geist", "sans-serif"],
        mono: ["JetBrains Mono", "monospace"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
      },
      backdropBlur: {
        xs: "2px",
        "12": "12px",
        "24": "24px",
        "32": "32px",
        "40": "40px",
        "64": "64px",
      },
      boxShadow: {
        glass: "0 8px 32px 0 rgba(0, 0, 0, 0.37)",
        "glass-sm": "0 4px 16px 0 rgba(0, 0, 0, 0.25)",
        "glass-highlight": "inset 0 1px 0 0 rgba(255, 255, 255, 0.15)",
        "glow-primary": "0 0 25px rgba(173, 198, 255, 0.25)",
        "glow-secondary": "0 0 25px rgba(208, 188, 255, 0.25)",
        "glow-emerald": "0 0 25px rgba(16, 185, 129, 0.35)",
        "glow-avatar": "0 0 35px rgba(16, 185, 129, 0.45)",
        "ring-emerald": "0 0 0 2px #10b981, 0 0 25px rgba(16, 185, 129, 0.4)",
      },
      animation: {
        float: "float 18s ease-in-out infinite alternate",
        "pulse-slow": "pulse 6s cubic-bezier(0.4, 0, 0.6, 1) infinite",
      },
      keyframes: {
        float: {
          "0%": { transform: "translate(0px, 0px) scale(1)" },
          "50%": { transform: "translate(30px, -30px) scale(1.05)" },
          "100%": { transform: "translate(-20px, 20px) scale(0.95)" },
        },
      },
    },
  },
  plugins: [],
}
